services:
    sheer.sub_prfx.listener:
        class: sheer\sub_prfx\event\listener
        arguments:
            - '@dbal.conn'
            - '%core.root_path%'
            - '@template'
            - '@request'
            - '@config'
            - '@config_text'
            - '@user'
        tags:
            - { name: event.listener }
